### ISSUE TITLE
Lab 03 - Clarification on Q3a

### ISSUE THREAD

**Issue by ecking** [DS4PS/cpp-525-fall-2020#10]
Hello @Dselby86 , I am just a little unsure of my tables and what I'm supposed to be referencing. 

Is question Q3a referencing the table we had to create in  Q2c? 

Here is what I did. For Q2c, I have a table of the OLS model 1 and FE with/out the intercept for Model 2. 

However, when I get down to question 3, it's asking about state intercepts. Should I be creating another table with the states and intercept in model 1 and in model 2 have the FE without the intercept? 

I'm slightly confused.

**Comment by Dselby86** [comment]
The question is asking for you to create 1 model that has the state intercept, and the other model that doesn't.  The predicted values will be the same, but the intercept of the two models will be different. Other questions ask you about interpreting what the two intercepts mean.

**Comment by Dselby86** [comment]
The wording is unclear for question 3. It is referring to the 1st and 2nd fixed effects model.
