### ISSUE TITLE
Stargazer HTML issues

### ISSUE THREAD

**Issue by TVK36692** [DS4PS/cpp-525-fall-2020#11]
I noticed the comment about having stargazer in the html style. Even when I knit the file, it comes out as html code when I do not set it as "text". Has anyone else experienced this?

Best,
TK

**Comment by lecy** [comment]
You need to add the results="asis" argument to the code chunk so the HTML gets embedded in the document when knitted instead of printing it as R output:

````
```{r, results="asis"}
````

**Comment by TVK36692** [comment]
Thank you!
