### ISSUE TITLE
Lab 05, Q1e clarification

### ISSUE THREAD

**Issue by RTrehern-ASU** [DS4PS/cpp-525-fall-2020#13]
In lab 5, Q1e states "Looking at the results from Q1d, do we still trust the results from Q1a? Why?"   

I think it meant to say "do we still trust the results from "Q1c" instead of "Q1a" but wanted to ask to be certain.  is this correct?

**Comment by Dselby86** [comment]
Yes. Do Q1c instead of Q1a. Thanks for asking

**Comment by ecking** [comment]
Thank you for asking. I was wondering the same thing!
