### ISSUE TITLE
Lab 4 Q1

### ISSUE THREAD

**Issue by Niagara1000** [DS4PS/cpp-525-fall-2020#14]
1. For **Q1a: (Produce a summary statistics table using stargazer)**: Is the table that the question is referring to?

- (PIC 1)

<img width="628" alt="Screen Shot 2020-11-15 at 9 29 33 AM" src="https://user-images.githubusercontent.com/46457863/99191988-21d7dc00-2725-11eb-9ac0-8259edc766c2.png">

<br>
<hr>
<br>

2. I also tried using `summary()` but it doesn't look like it returned the output that the question was asking for..
<br>

- (PIC 2)

### _**with intercept**_
<img width="661" alt="Screen Shot 2020-11-14 at 5 47 11 PM" src="https://user-images.githubusercontent.com/46457863/99192046-82671900-2725-11eb-888c-ade4dd2627a0.png">

<br>
<hr>
<br>

- (PIC 3)

### _**without intercept**_
<img width="575" alt="Screen Shot 2020-11-14 at 5 47 23 PM" src="https://user-images.githubusercontent.com/46457863/99192054-927ef880-2725-11eb-8604-923e341818ad.png">

<br>
<hr>
<br>

3. Referring to pics 2 and 3, would `Estimate` be the same as "mean"?

<br>
<hr>
<br>

Thank you!

**Comment by Dselby86** [comment]
In the stargazer command, if you enter a data frame as an argument it should output a summary statistics table.
