### ISSUE TITLE
Lab 07 - Q1 and Q2

### ISSUE THREAD

**Issue by ecking** [DS4PS/cpp-525-fall-2020#16]
Hello, I'm working on lab 7 and I'm a little confused. I copied the data to excel and identified the matches. I plugged them into the first question in part 1.  I then ran the code in the lab for Q2 however when I get to question 2a it's asking for dat.matched. Where did dat.matched come from? Am I supposed to edit the code in Question 2 to reflect a dat.matched? I'm just not sure what to do here.

**Comment by RTrehern-ASU** [comment]
@ecking,
I don't know if this is correct or not, but I created a new data frame using the matches from Q1.  After entering the matches into the variable "ids", I used the following code to turn "ids" into a new data frame and called it "dat.matched": 

```{r}
dat.matched <- as.data.frame(dat[ ids, ])
```

After creating the new data frame it seems to work; but again, I don't know if this was necessarily the "right" solution.

Anyone else dealt with this issue yet?
