### ISSUE TITLE
Drop lowest lab grade

### ISSUE THREAD

**Issue by JasonSills** [DS4PS/cpp-525-fall-2020#17]
Hi @Dselby86,

Just wanted to clarify the grading of our labs. I see that the lowest grade is dropped. I'm just checking to see that if we are satisfied with our grade for 1-6 does this make lab 7 optional? Or are we still required to submit all 7, but the lowest will be dropped? 

Thank you!

**Comment by Dselby86** [comment]
While I would prefer if everyone did the 7th lab, there are other people
who have missed labs that I think are banking on dropping that grade.  So
it wouldn't be fare to require all labs to be turned in order to drop the
lowest grade.

**Comment by TVK36692** [comment]
Will the Lab04 rework be graded or commented on? I just wanted to know if I made the right corrections. Thank you for the clarification!

**Comment by Dselby86** [comment]
I will get to it tonight. Thanks for the reminder.
