### ISSUE TITLE
Help Ramping Back Up

### ISSUE THREAD

**Issue by TVK36692** [DS4PS/cpp-525-fall-2020#2]
Hi, I had a gap in the program of almost a year now and I was wondering the best way to get ramped back up for this first lab. Can you point me in the direction of any other labs in previous courses that will give me the pieces to get this dataset ready in Lab 01?

Thank you for any help possible.

Best,
TK

**Comment by Dselby86** [comment]
I responded to the email that you sent me, But it might be helpful for other people to have this resource.

The two prerequisites for this class are below. 

https://ds4ps.org/cpp-524-sum-2020/ 
https://ds4ps.org/cpp-526-fall-2020/schedule/  

If anyone thinks that the other courses in the program would be useful, let me know.
