### ISSUE TITLE
Lab 2 Coefficients Meaning

### ISSUE THREAD

**Issue by Niagara1000** [DS4PS/cpp-525-fall-2020#7]
HI Prof @Dselby86 and @lecy ,

Can I please get an explanation of the variables/coefficients in this table? I am super lost and running out of time. I read through all the material for this week, and I am still stuck, and I don't know why. :( 

I am attaching the picture below. This is part of Lab 2 where we analyze the effects of greening on vandalizing acts.

<img width="325" alt="Screen Shot 2020-10-26 at 9 42 25 PM" src="https://user-images.githubusercontent.com/46457863/97261505-30913a00-17dc-11eb-8518-49a0cbe15039.png">

<br><br>

Reference: https://ds4ps.org/pe4ps-textbook/labs/diff-in-diff-lab.html

**Comment by Dselby86** [comment]
Intercept is the Average number of calls at the start of the study
Treatment is the effect of being in the treatment group, but have not received the treatment
Post Treatment is the effect of being in the control group during the Post-Treatment Period
DIff in Diff is the effect of being in the treatment and having received the treatment

**Comment by lecy** [comment]
Just remember that the mean of each group is constructed by adding coefficients, so most cannot be interpreted directly: 

![image](https://user-images.githubusercontent.com/1209099/97270654-bfa64e00-17ec-11eb-9dd8-bb10e824466f.png)
