### ISSUE TITLE
Week 3 Lecture

### ISSUE THREAD

**Issue by Niagara1000** [DS4PS/cpp-525-fall-2020#8]
Hi Professor @Dselby86 ,

Will we be having a lecture tomorrow evening at 7 pm (Thursday, Oct 29th)?

Thank you!

**Comment by Dselby86** [comment]
Yes, I'll see you then if you can make it

**Comment by JayCastro** [comment]
Do the videos ever get posted if we miss them ? If so where because I haven't been able to find them

**Comment by Dselby86** [comment]
I couldn't figure out how to post them yet. But i"m working on it. Only two people came to last week's session, so I answered personalized questions for them.
